services:
  - type: web
    name: codearena-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ADMIN_PASSWORD
        value: admin123
      - key: FLASK_SECRET_KEY
        value: codearena_secret_2026
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        value: mongodb+srv://shenesz13_db_user:4mpJ0eNgzhxubfcF@cluster0.aykblpn.mongodb.net/codearena?appName=Cluster0
      - key: JUDGE0_API_URL
        value: https://judge0-ce.p.rapidapi.com
